#!/bin/sh

awk '\
	/define VERSION_MAJOR/ { printf "%d.", $3 }\
	/define VERSION_MINOR/ { printf "%d", $3 } \
	/define VERSION_APPEND/ { val=$3; gsub(/"/,"",val); printf  "-%s", val }\
	END { print "\n" }' main.c

